name: propagou
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  quickalert: ^1.0.1
  loading_animation_widget: ^1.2.0+4
  validatorless: ^1.2.3
  flutter_awesome_select: ^6.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
          weight: 800